# Generated by Django 4.1.1 on 2022-09-22 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sparkleApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderedService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_text", models.CharField(max_length=100)),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sparkleApp.master",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sparkleApp.service",
                    ),
                ),
            ],
        ),
    ]
