# Generated by Django 4.1.1 on 2022-09-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sparkleApp", "0002_orderedservice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("made_by", models.CharField(max_length=10)),
                ("made_on", models.DateTimeField(auto_now_add=True)),
                ("amount", models.IntegerField()),
                (
                    "order_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("checksum", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
